name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "59 6 28 * *"

jobs:
  upgrade:
    permissions:
      contents: write
      pull-requests: write
    uses: browniebroke/github-actions/.github/workflows/poetry-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GITHUB_TOKEN }}
